# Generated by Django 3.2.16 on 2024-08-20 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_gift', models.CharField(max_length=50, verbose_name='Код gift')),
                ('url_gift', models.URLField(blank=True, null=True, verbose_name='Url gift')),
                ('usefull_url', models.URLField(max_length=50, verbose_name='usefull_url')),
                ('track_file', models.URLField(blank=True, null=True, verbose_name='Файл')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='payment_url')),
                ('ios_payment', models.URLField(blank=True, null=True, verbose_name='ios_payment ')),
                ('help_install_file', models.URLField(blank=True, null=True, verbose_name='help_install_file ')),
                ('present_on_pc', models.URLField(blank=True, null=True, verbose_name='present_on_pc ')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('vk', 'Vk'), ('tg', 'Telegram')], max_length=50, verbose_name='platform ')),
                ('days_of_week', models.CharField(blank=True, max_length=50, verbose_name='Дни недели')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Напоминания',
                'verbose_name_plural': 'Напоминание',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='user_id')),
                ('username', models.CharField(max_length=50, verbose_name='username ')),
                ('platform', models.CharField(choices=[('vk', 'Vk'), ('tg', 'Telegram')], max_length=50, verbose_name='platform ')),
                ('role', models.CharField(choices=[('parent', 'Родитель'), ('speech_therapist', 'Логопед')], max_length=50, verbose_name='role ')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfile',
                'ordering': ('user_id',),
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_id'], name='bot_userpro_user_id_aa58bd_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.userprofile'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['code_gift'], name='bot_content_code_gi_3e5c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id'], name='bot_notific_user_id_20a77d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['platform'], name='bot_notific_platfor_ac006c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['time'], name='bot_notific_time_233a92_idx'),
        ),
    ]
