# Generated by Django 3.2.16 on 2024-08-02 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_gift', models.CharField(max_length=50, verbose_name='Код gift')),
                ('url_gift', models.URLField(blank=True, null=True, verbose_name='Url gift')),
                ('usefull_url', models.CharField(max_length=50, verbose_name='usefull_url')),
                ('track_file', models.BinaryField(verbose_name='Файл')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='payment_url')),
                ('ios_payment', models.BinaryField(verbose_name='ios_payment ')),
                ('help_install_file', models.BinaryField(verbose_name='help_install_file ')),
                ('present_on_PK', models.BinaryField(verbose_name='present_on_PK ')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Платформа')),
                ('days_of_week', models.CharField(max_length=50, verbose_name='Дни недели')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Напоминания',
                'verbose_name_plural': 'Напоминание',
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='user_id')),
                ('username', models.CharField(max_length=50, verbose_name='username ')),
                ('platform', models.CharField(choices=[('vk', 'Vk'), ('tg', 'Telegram')], max_length=50, verbose_name='platform ')),
                ('role', models.CharField(choices=[('parent', 'Родитель'), ('speech_therapist', 'Логопед')], max_length=50, verbose_name='role ')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfile',
                'ordering': ('user_id',),
            },
        ),
    ]
