# Generated by Django 3.2.16 on 2024-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_notification_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='platform',
            field=models.CharField(choices=[('vk', 'Vk'), ('tg', 'Telegram')], max_length=50, verbose_name='platform '),
        ),
    ]
