# Generated by Django 3.2.16 on 2024-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20240815_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='help_install_file',
            field=models.URLField(verbose_name='Файл помощи по установке'),
        ),
        migrations.AlterField(
            model_name='content',
            name='ios_payment',
            field=models.URLField(verbose_name='Файл оплаты для iOS'),
        ),
        migrations.AlterField(
            model_name='content',
            name='present_on_pk',
            field=models.URLField(blank=True, null=True, verbose_name='Файл для ПК'),
        ),
        migrations.AlterField(
            model_name='content',
            name='track_file',
            field=models.URLField(verbose_name='Файл для отслеживания'),
        ),
    ]
