# Generated by Django 3.2.16 on 2024-08-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_notification_days_of_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
