# Generated by Django 3.2 on 2024-08-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240811_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='days_of_week',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=50, verbose_name='Дни недели'),
        ),
    ]
